export enum OrderStatus {
    NOT_PROCESSED_YET = "NOT_PROCESSED_YET",
    PENDING = "PENDING",
    PROCESSING = "PROCESSING",
    SHIPPING = "SHIPPING",
    DELIVERED = "DELIVERED",
    CANCELLED = "CANCELLED"
}